more script
Signed-off-by: Bishal Thapa <bishal.thapa@trustly.com>

diff --git a/namespace/bank-integration/bain-api-proxy/move-swish-report-script.yaml b/namespace/bank-integration/bain-api-proxy/move-swish-report-script.yaml
--- a/namespace/bank-integration/bain-api-proxy/move-swish-report-script.yaml
+++ b/namespace/bank-integration/bain-api-proxy/move-swish-report-script.yaml
@@ -5,4 +5,21 @@ metadata:
   namespace: bank-integration
 data:
   process_s3_report.sh: |
-    echo "here" 
+    ENDPOINT="http://swish-report.product/report/api/v1/processing-accounts?partnerBank=Northmill"
+    
+    
+    # Fetch the response from the API
+    response=$(curl -s "$ENDPOINT")
+    if [ -z "$response" ]; then
+      echo "Failed to fetch API response. Exiting." >&2
+      exit 1
+    fi
+    
+    # Filter processing accounts with partnerBank = "Northmill"
+    northmill_accounts=$(echo "$response" | jq -c '.[] | select(.partnerBank == "Northmill")')
+    if [ -z "$northmill_accounts" ]; then
+      echo "No accounts with partnerBank 'Northmill' found. Exiting." >&2
+      exit 1
+    fi
+    
+    echo $northmill_accounts
